### ISSUE TITLE
Mobile Toggle float to left when resized in admin view

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#11]
Mobile Menu seems to float to left when resized in Customizer Window or in Logged-in mode, makes it little difficult to work on mobile menu related design.

A user can get the menu toggle back when Menu breakapoint is resized. I assume, we need to reload this page at some point if a user is logged-in.

![image](https://user-images.githubusercontent.com/34836534/54984987-ffd09980-4fd5-11e9-8049-ba166635cfcc.png)

**Comment by genesisplugins** [comment]
What are the Primary Header > Mobile Layout settings?

**Comment by rockingaryan** [comment]
It is Logo in left and Toggle in right.

![image](https://user-images.githubusercontent.com/34836534/55125059-839d9980-512e-11e9-8417-c3da53076919.png)

**Comment by rockingaryan** [comment]
This feature is moved in Pro version. Issue need to be moved on add-on page.

**Comment by genesisplugins** [comment]
Was there a logo set in the original test?

**Comment by rockingaryan** [comment]
Sorry i forget. I think it was not, but we can say LOGO = Title area. so title area was hiding.

**Comment by rockingaryan** [comment]
It was title area, tested on https://free.wpdev.in

It is solved in newer version but sometime menu toggle float to left in some settings when resized for mobile.

**Comment by genesisplugins** [comment]
Ok, closing for now. I think this only happens when there is no logo/title-area which can't really be prevented.
