### ISSUE TITLE
Mobile Menu doesn’t show Secondary Menu until window is resized

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#12]
Mobile Menu doesn’t show secondary menu items untill window is resized. Not any user will resize window in mobile so there is no chance to view the secondary menu using mobile.

Tested on android mobile and it is not showing.

![2019-03-26 14-58-41 2019-03-26 14_59_31](https://user-images.githubusercontent.com/34836534/54985993-d7e23580-4fd7-11e9-8382-14830e9f2b19.gif)

**Comment by rockingaryan** [comment]
This feature is moved in Pro version. Issue need to be moved on add-on page.

**Comment by genesisplugins** [comment]
Fixed with fbb0dfd72943ffe2ac9ffa815ada3cf5c7b4a0f4
