### ISSUE TITLE
Add option to enable full width content layout on Post page

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#17]
Blog / Archive > Post Grid. 

How about adding ENABLE full width content LAYOUT option for is_home? This will Help users to quickly change the Grid Layout.

Full width content is useful when user want to choose 3 or 4 columns Grid layout for blog posts.

**Comment by rockingaryan** [comment]
This feature is moved in Pro version. Issue need to be moved on add-on page.

**Comment by genesisplugins** [comment]
This can be done by changing the blog page's layout so another setting could cause some confusion. Will close this for now.
