### ISSUE TITLE
CSS output Type doesn’t seems to work

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#2]
General Settings → Assets.

CSS Output is default and no change are being applied on type of CSS, or how the beautification will apply to stylesheets.

Currently, we have the following CSS files.

1. assets/css/genesis-customizer.css
2. assets/css/max-width-896px.css
3. assets/css/min-width-896px.css
4. assets/css/simple-social-icons.css

How these type of minification will work?
- Expanded
-  Nested
-  Compact
-  Compressed

**Comment by genesisplugins** [comment]
Removed this feature for now
