### ISSUE TITLE
Removing Breakpoints feature result in CSS not working

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#20]
Breakpoints is a feature moved in the pro add-on.

The enqueued stylesheets now not giving the breakpoint value, result no CSS is working from mobile.css or desktop.css file

This breaks the content-sidebar and other layouts. This will also result a different layout, no css applied to various HTML elements which is added in both the CSS file.

![image](https://user-images.githubusercontent.com/34836534/55133349-63c89e80-514b-11e9-8ebf-c4ff4c8774b6.png)

**Comment by rockingaryan** [comment]
896 should be a default value in media max and min.

**Comment by genesisplugins** [comment]
Fixed 12f5cb51c6659c3fed027d7b85d6ecbb37da7453
