### ISSUE TITLE
Additional Customization for Menu Toggle

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#25]
Menus > Menu Toggle. 

Add border and shadow color and hover/focus for menu toggle and sub toggle. It takes the border and shadow from Base Styles > Buttons.

![image](https://user-images.githubusercontent.com/34836534/55147832-22e18180-516d-11e9-8bd5-1d89046f71fd.png)

Menu toggle should not be treated as a normal button so its styling should be different from normal button.

**Comment by genesisplugins** [comment]
Fixed in last commit
