### ISSUE TITLE
Changing margin in Base Styles elements revert other changes to default

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#26]
Genesis Customizer Free > Base styles.

After margin changes in typography size, margin result other changes to revert back to the default color, positioning in Customizer. Here are some of the highlighted errors.

1. Base Styles > Body. margin bottom value not showing in customizer. Color revert back to default.
2. Base Styles > Headings. margin top and bottom value not showing in customizer. Sometime color revert back to default.
3. Base Styles > Buttons. Text and Text hover, Border and Border Hover value, Typography variant is not showing in Customizer.

I was not able to record that default color changes but here margin not showing.

![Untitled 2019-03-28 19_59_13](https://user-images.githubusercontent.com/34836534/55165850-21777f80-5194-11e9-95a7-841a617c2a9c.gif)

**Comment by rockingaryan** [comment]
Adding border value in Menus > Secondary result changes back to the default secondary Background and link color without border.

This happen first time. It works when i try to record screenshot.

**Comment by rockingaryan** [comment]
Single Post/Page > Entry. same customizer problem.

![image](https://user-images.githubusercontent.com/34836534/55168160-5554a400-5198-11e9-9194-490f9742a873.png)

**Comment by genesisplugins** [comment]
- [x] Body
- [ ] Headings
- [ ] Buttons
