### ISSUE TITLE
Site Footer Widgets text and links hides due to No z-index value

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#28]
I apologize, seems like it was my fault of not clicking and selecting the footer widgets link during the first test of the plugin. I was feeling something like this but forget to test.

It uses footer-widgets::before css for overlay background without z-index: -1; so that we  are not able to click link and select/copy text.

![image](https://user-images.githubusercontent.com/34836534/55170333-5ab3ed80-519c-11e9-9cc5-3445eb546b01.png)

Move this overlay cover with negative value adding z-index: -1;  in .footer-widgets:before (all.css) will solve this issue.

**Comment by genesisplugins** [comment]
Fixed in 7725683065fe14c3d7f0bfcd3182631fbfcefd71
