### ISSUE TITLE
Primary Header Layout and Secondary menu tip link

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#29]
Header > Primary Header. 
Suppose We choose Desktop Layout 2. Here Secondary Menu remains left. Here is a TIP link to manage Secondary Menu alignment so we one will click that,

Unfortunately, going through this link hide the full-width setting and other alignment also not work. One will need to go through Menus > Secondary Menu to change the alignment.

So TIP link is redirecting a user to secondary menu but alignment not work after going through TIP link. User will need to go through manually Genesis Customizer > Menus > Secondary and then change alignment.

![image](https://user-images.githubusercontent.com/34836534/55203951-536bfe80-51f3-11e9-86ab-cca1af03012e.png)

**Comment by genesisplugins** [comment]
Updated the tip to this:

![image](https://user-images.githubusercontent.com/21374227/55210032-7c56b880-5220-11e9-8adb-0d87d37c1409.png)
