### ISSUE TITLE
Working with default and Custom CSS breakpoints.

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#3]
General Settings → Breakpoints.

The Plugin is using 896px as a breakpoint which should be changed to a common gloabl CSS media queries used by child themes.

Genesis Sample is using 960px. 
SEOthemes is using 896px.

Currently, Only specific classes are added with custom breakpoints. Thus, we will have two to deal with two media queries for a different container.

I set the custom Breakpoints to 960px from 896px. Here, hero section have  @media  (min-width: 960px)  but some other elements use the default media query which is 896px.

This will be interesting to see, how we can find the elements which will work under a custom breakpoint (find the css inline or Restricting the Stylesheet Media to a number from “ALL”).
I assume that we are adding an additional media query which will work depending on the number(960px) of default media (896px) query.

![image](https://user-images.githubusercontent.com/34836534/54920864-5d0f1100-4f2a-11e9-90b6-d30bd2662ed9.png)

**Comment by genesisplugins** [comment]
There are 2 breakpoint settings - global and mobile menu.

The mobile menu is separate to the global breakpoint to allow more control.

Are the other elements you are referring to related to the menu?

**Comment by rockingaryan** [comment]
Some Elements like Header Left and Header Right conflicts between 896px-Custom Breakpoints.
![2019-03-26 12-18-41 2019-03-26 12_20_51](https://user-images.githubusercontent.com/34836534/54979314-dc532200-4fc8-11e9-9bbf-c767c8d19f5a.gif)

**Comment by rockingaryan** [comment]
This feature is moved in Pro version. Issue need to be moved on add-on page.

**Comment by genesisplugins** [comment]
This is now fixed
