### ISSUE TITLE
Primary Header and Customizer

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#30]
Header > Primary Header background and border changes not visible in customizer. Here are some issues which need to be solved

1. Changing site header background color or border giving not working. Shadow change is working
2. Add border width for border top and bottom. I thought it was there.  

One setting Found it under Menus > Primary / Secondary Menu.  Add a TIP text for this.

![image](https://user-images.githubusercontent.com/34836534/55204098-d7be8180-51f3-11e9-9256-333495503c6c.png)

**Comment by genesisplugins** [comment]
Fixed around 7725683065fe14c3d7f0bfcd3182631fbfcefd71
