### ISSUE TITLE
Secondary Sidebar Widget Area not available

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#31]
One can enable Secondary sidebar from Genesis > Theme Settings > Layouts but it not activated the secondary sidebar in widgets section.

![image](https://user-images.githubusercontent.com/34836534/55275855-54478200-5312-11e9-9bf8-2fc7ea8b76f5.png)

**Comment by genesisplugins** [comment]
Fixed in ee29849
