### ISSUE TITLE
Entry Content float to right on archive and post page

### ISSUE THREAD

**Issue by aryanrajseo** [genesisplugins/genesis-customizer#32]
1. Entry content float to right, p for .archive.
2. No spacing or margin bottom on each post list on archive page.

![screencapture-test-wpdev-in-wp-admin-customize-php-2019-03-30-17_35_24](https://user-images.githubusercontent.com/34836534/55275894-b99b7300-5312-11e9-9a87-002689416f8d.png)

**Comment by genesisplugins** [comment]
Fixed in ee29849
