### ISSUE TITLE
Fixed site header conflicting with site-inner contents

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#6]
Free version of plugin add position: fixed; in site header makes it difficult to view hero section and other content output after site header.
Pro version is working fine. Take a look on both the site.

Add an option in Customizer to make the site header fixed which add some class using js and then target that CSS to have a fixed header.

Remember, we will need to fix the site-inner container according to the position of the site header.

**Comment by rockingaryan** [comment]
Fixed Header is a feature for Pro version only?

Free version of plugin enables fixed site header by default. Add an option to enable it from: Header > Primary Header

**Comment by genesisplugins** [comment]
Fixed
