### ISSUE TITLE
Fixed site-header and site-inner margin

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#7]
I am not able to get how the margin-top: 0; remains default with both the version. Are you able to see any changes?

**The Problems:**

1. Fixed site header is default in free version. We should to move it as a pro feature?
2. Fixed site header behaviour should add margin-top: 200px; (match height) like margin in site-inner to view the hero section.
3. Pro version is removing the position: fixed; class so margin-top: 0; will work.

We need to make a feature switch here. Because site header is working opposite depending on the version. What do you think?

**Comment by genesisplugins** [comment]
Fixed in 0.1.3
