### ISSUE TITLE
Split Navigation to the left and right and not menu items.

### ISSUE THREAD

**Issue by rockingaryan** [genesisplugins/genesis-customizer#8]
Header > Primary Header. Desktop Layout 2nd.

The visual image shows that Primary menu should be in left and Secondary Menu in Right.
Currently, Only the Primary menu is splitting menu items to left and right.

![image](https://user-images.githubusercontent.com/34836534/54981638-c8122380-4fce-11e9-8144-7a069d910546.png)

**Comment by rockingaryan** [comment]
**Here is an additional Idea.**

Add a conditional tag if secondary menu is not set, split Primary navigation, otherwise it should Primary Menu in left and Secondary in Right.

**Comment by rockingaryan** [comment]
We should also move some header type layout in Pro version.

**Comment by rockingaryan** [comment]
This feature is moved in Pro version. Issue need to be moved on add-on page.

**Comment by genesisplugins** [comment]
This one is tricky, at the moment the logo is moved to the center of the primary menu. There needs to be an equal number of menu items on each side for it to be centerred. Leaving functionality as is for now.
